class LoginError(Exception):
    pass


class SaveReplayError(Exception):
    pass
